---
# tasks file for db-tier
- name: Install PostgreSQL
  yum:
    name: postgresql-server
    state: present

- name: Check if PostgreSQL database is initialized
  command: postgresql-check-db-dir /var/lib/pgsql/data
  register: r_pg_check_output
  changed_when: r_pg_check_output == 1
  ignore_errors: yes

- name: PostgreSQL database initialization.
  shell: postgresql-setup initdb
  when: r_pg_check_output.rc != 0

- name: Start PostgreSQL
  service:
   name: postgresql
   state: started
   enabled: yes
